version = 1

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jest"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"